### PR TITLE
i18n for picker button

### PR DESCRIPTION
**Pull request by gh-quentin-estrach**

### CODE REVIEW

**Comment by Tronix117** [comment]
@shiv19 could this be accepted ? Main langage should be respected, so if there is no translations on the device, as well give the option to customize those labels

**Comment by pedromorgan** [comment]
This would be handy, in my case to customise Label to "Set", "Start" etc on a system

**Comment by Tronix117** [comment]
@shiv19 could you give us an ETA for this PR to land in npm ? Thanks !

**Comment by shiv19** [comment]
Sorry for the delay, @Tronix117 

Published it just now as 1.1.3

**Pull request merged**
